---
- name: "Create a directory to download binaries"
  file: path={{ cri_release_directory }} state=directory

- name: "Get Containerd and CRI-Containerd"
  get_url:
    validate_certs: "no"
    url: "https://storage.googleapis.com/cri-containerd-staging/cri-containerd-{{ cri_containerd_release_version }}.tar.gz"
    dest: "{{ cri_release_directory }}"
    mode: 0755

- name: "Unpack Containerd and CRI-Containerd"
  unarchive:
    src: "{{ cri_release_directory }}cri-containerd-{{ cri_containerd_release_version }}.tar.gz"
    dest: "{{ cri_release_directory }}"

- name: "Install the containerd and cri-containerd binaries" 
  copy:
    src: "{{ cri_release_directory }}usr/local/bin/{{ item }}"
    dest: "{{ local_bin_dir }}{{ item }}"
  with_items:
    - containerd
    - containerd-stress
    - containerd-shim
    - cri-containerd
    - ctr

- name: "Install runc"
  copy:    
    src: "{{ cri_release_directory }}usr/local/sbin/{{ item }}"
    dest: "{{ local_sbin_dir }}{{ item }}"
  with_items:
    - runc

- name: "Copy containerd systemd service unit"
  template: src=containerd.service dest=/etc/systemd/system/containerd.service

- name: "Copy cri-containerd systemd service unit"
  template: src=cri-containerd.service dest=/etc/systemd/system/cri-containerd.service
